[GenesisDoc]
  GenesisTime = 2019-01-23T09:45:05Z
  ChainName = "BurrowChain_D6C20E"
  [GenesisDoc.Params]
    ProposalThreshold = 3
  [GenesisDoc.GlobalPermissions]
    [GenesisDoc.GlobalPermissions.Base]
      Perms = "send | call | createContract | createAccount | bond | name | proposal | input | batch | hasBase | hasRole"
      SetBit = "root | send | call | createContract | createAccount | bond | name | proposal | input | batch | hasBase | setBase | unsetBase | setGlobal | hasRole | addRole | removeRole"

  [[GenesisDoc.Accounts]]
    Address = "44E32AD7C983146F6D8B4DBF6D22959E89A92F67"
    PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"94E6D699FC57B3575E8E5A56CA18CF9632430A31D566705B4C3CAA06134F58B0\"}"
    Amount = 99999999999999
    Name = "Full_0"
    [GenesisDoc.Accounts.Permissions]
      [GenesisDoc.Accounts.Permissions.Base]
        Perms = "root | send | call | createContract | createAccount | bond | name | proposal | input | batch | hasBase | setBase | unsetBase | setGlobal | hasRole | addRole | removeRole"
        SetBit = "root | send | call | createContract | createAccount | bond | name | proposal | input | batch | hasBase | setBase | unsetBase | setGlobal | hasRole | addRole | removeRole"

  [[GenesisDoc.Accounts]]
    Address = "1A723EC91525B0677A86368A5F20F68B25D44C6E"
    PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"73757FAA063959ECDACAB1D845786F196A792811EA0D1E638AD0A1BD8B1DF03B\"}"
    Amount = 99999999999999
    Name = "Full_1"
    [GenesisDoc.Accounts.Permissions]
      [GenesisDoc.Accounts.Permissions.Base]
        Perms = "root | send | call | createContract | createAccount | bond | name | proposal | input | batch | hasBase | setBase | unsetBase | setGlobal | hasRole | addRole | removeRole"
        SetBit = "root | send | call | createContract | createAccount | bond | name | proposal | input | batch | hasBase | setBase | unsetBase | setGlobal | hasRole | addRole | removeRole"

  [[GenesisDoc.Accounts]]
    Address = "6E536049FB8134A3DD55AE26612E496FEBC856D5"
    PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"94D4F25C19FCEC53711FC77B839EBEF299E8467DCFB73A7AB504DE09912EBDFB\"}"
    Amount = 99999999999999
    Name = "Full_2"
    [GenesisDoc.Accounts.Permissions]
      [GenesisDoc.Accounts.Permissions.Base]
        Perms = "root | send | call | createContract | createAccount | bond | name | proposal | input | batch | hasBase | setBase | unsetBase | setGlobal | hasRole | addRole | removeRole"
        SetBit = "root | send | call | createContract | createAccount | bond | name | proposal | input | batch | hasBase | setBase | unsetBase | setGlobal | hasRole | addRole | removeRole"

  [[GenesisDoc.Accounts]]
    Address = "A72DF4F1AE055B11201123A9DDDCBC12E7E5DF2B"
    PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"A863FEAD151F388B781D62BEEA26712E59DD3AF0E2F478DA260F3C4AA5EE8904\"}"
    Amount = 99999999999999
    Name = "Full_3"
    [GenesisDoc.Accounts.Permissions]
      [GenesisDoc.Accounts.Permissions.Base]
        Perms = "root | send | call | createContract | createAccount | bond | name | proposal | input | batch | hasBase | setBase | unsetBase | setGlobal | hasRole | addRole | removeRole"
        SetBit = "root | send | call | createContract | createAccount | bond | name | proposal | input | batch | hasBase | setBase | unsetBase | setGlobal | hasRole | addRole | removeRole"

  [[GenesisDoc.Accounts]]
    Address = "5603A906C480EB96803649C3D97F3075C849061C"
    PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"B0FD7AB0FAC3A68D864D273E8750E089E52000CC7561B9648BE049F549BA9A44\"}"
    Amount = 99999999999999
    Name = "Full_4"
    [GenesisDoc.Accounts.Permissions]
      [GenesisDoc.Accounts.Permissions.Base]
        Perms = "root | send | call | createContract | createAccount | bond | name | proposal | input | batch | hasBase | setBase | unsetBase | setGlobal | hasRole | addRole | removeRole"
        SetBit = "root | send | call | createContract | createAccount | bond | name | proposal | input | batch | hasBase | setBase | unsetBase | setGlobal | hasRole | addRole | removeRole"

  [[GenesisDoc.Accounts]]
    Address = "D584FFF08EB31E03AD83ACB35928B01C008AD778"
    PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"328120F35B78653B64A8EE6C187D958E1C043B1F798DC4E78CF55369C0492BA6\"}"
    Amount = 99999999999999
    Name = "Full_5"
    [GenesisDoc.Accounts.Permissions]
      [GenesisDoc.Accounts.Permissions.Base]
        Perms = "root | send | call | createContract | createAccount | bond | name | proposal | input | batch | hasBase | setBase | unsetBase | setGlobal | hasRole | addRole | removeRole"
        SetBit = "root | send | call | createContract | createAccount | bond | name | proposal | input | batch | hasBase | setBase | unsetBase | setGlobal | hasRole | addRole | removeRole"

  [[GenesisDoc.Accounts]]
    Address = "A297DBBD7FF192CF9F4B3986F6D1FC219DDBB2C1"
    PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"6436F6CEA37A32D7551A9E86310F20B8E18471486AACBD864E098CB9EA28B02B\"}"
    Amount = 99999999999999
    Name = "Full_6"
    [GenesisDoc.Accounts.Permissions]
      [GenesisDoc.Accounts.Permissions.Base]
        Perms = "root | send | call | createContract | createAccount | bond | name | proposal | input | batch | hasBase | setBase | unsetBase | setGlobal | hasRole | addRole | removeRole"
        SetBit = "root | send | call | createContract | createAccount | bond | name | proposal | input | batch | hasBase | setBase | unsetBase | setGlobal | hasRole | addRole | removeRole"

  [[GenesisDoc.Accounts]]
    Address = "7EFB026E3469760C8F2364A1070767264475D319"
    PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"9387024AD4E5C0645FCA292669889AACEDAF4B06D14E63D6C5C40F4B2A291588\"}"
    Amount = 99999999999999
    Name = "Full_7"
    [GenesisDoc.Accounts.Permissions]
      [GenesisDoc.Accounts.Permissions.Base]
        Perms = "root | send | call | createContract | createAccount | bond | name | proposal | input | batch | hasBase | setBase | unsetBase | setGlobal | hasRole | addRole | removeRole"
        SetBit = "root | send | call | createContract | createAccount | bond | name | proposal | input | batch | hasBase | setBase | unsetBase | setGlobal | hasRole | addRole | removeRole"

  [[GenesisDoc.Accounts]]
    Address = "8FE8F26E0F50BE83AD42CF6BC490D267532F3509"
    PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"511B281CC4EEF65148D361BBDFD9D645D2B8C271BA42B6EA959694606114FCDE\"}"
    Amount = 99999999999999
    Name = "Full_8"
    [GenesisDoc.Accounts.Permissions]
      [GenesisDoc.Accounts.Permissions.Base]
        Perms = "root | send | call | createContract | createAccount | bond | name | proposal | input | batch | hasBase | setBase | unsetBase | setGlobal | hasRole | addRole | removeRole"
        SetBit = "root | send | call | createContract | createAccount | bond | name | proposal | input | batch | hasBase | setBase | unsetBase | setGlobal | hasRole | addRole | removeRole"

  [[GenesisDoc.Accounts]]
    Address = "A6227532C81022F9E8E3C15D5F445CEB28E40B18"
    PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"505B20308B035C5DD3D616810695FD7FE8AA77E4636E852C42D5A17D3CA7CFB0\"}"
    Amount = 99999999999999
    Name = "Full_9"
    [GenesisDoc.Accounts.Permissions]
      [GenesisDoc.Accounts.Permissions.Base]
        Perms = "root | send | call | createContract | createAccount | bond | name | proposal | input | batch | hasBase | setBase | unsetBase | setGlobal | hasRole | addRole | removeRole"
        SetBit = "root | send | call | createContract | createAccount | bond | name | proposal | input | batch | hasBase | setBase | unsetBase | setGlobal | hasRole | addRole | removeRole"

  [[GenesisDoc.Accounts]]
    Address = "509514A37A488DB020B1674A85DAB39F71A25E55"
    PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"0075F03CF0046C255861C889C06B4945436156F5E8172CA08E50B853E0698D7D\"}"
    Amount = 9999999999
    Name = "Participant_0"
    [GenesisDoc.Accounts.Permissions]
      [GenesisDoc.Accounts.Permissions.Base]
        Perms = "send | call | name | proposal | input | hasRole"
        SetBit = "send | call | name | proposal | input | hasRole"

  [[GenesisDoc.Accounts]]
    Address = "B0C0091ADBE68B551CE0BDF6F893DB4E692B85F4"
    PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"87C945917707B1054FB7EF3BA234C1E70B5C367C0493571FD45871AA73B69182\"}"
    Amount = 9999999999
    Name = "Participant_1"
    [GenesisDoc.Accounts.Permissions]
      [GenesisDoc.Accounts.Permissions.Base]
        Perms = "send | call | name | proposal | input | hasRole"
        SetBit = "send | call | name | proposal | input | hasRole"

  [[GenesisDoc.Accounts]]
    Address = "780DE7472E7388C59E25CDD98BE17BFFA9160E1C"
    PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"1CB86132FA5380C2FC0081A2B01EA32C9F761F2AB468394DA58E1A098B0F4713\"}"
    Amount = 9999999999
    Name = "Participant_2"
    [GenesisDoc.Accounts.Permissions]
      [GenesisDoc.Accounts.Permissions.Base]
        Perms = "send | call | name | proposal | input | hasRole"
        SetBit = "send | call | name | proposal | input | hasRole"

  [[GenesisDoc.Accounts]]
    Address = "1C22DECF7C5B5A457934D2AD07991F6894E7CBDA"
    PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"FFD1EB53519EADDD3472690D02913039DBE2B915CA7C248AB50BE6331ECDF529\"}"
    Amount = 9999999999
    Name = "Participant_3"
    [GenesisDoc.Accounts.Permissions]
      [GenesisDoc.Accounts.Permissions.Base]
        Perms = "send | call | name | proposal | input | hasRole"
        SetBit = "send | call | name | proposal | input | hasRole"

  [[GenesisDoc.Accounts]]
    Address = "B6B231F246A2E337634A153F696273A223E8ACC1"
    PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"A5E90E3929C57AF705B1B41B94A9890A20E90E364A4301C0950F6BAE65C7A697\"}"
    Amount = 9999999999
    Name = "Participant_4"
    [GenesisDoc.Accounts.Permissions]
      [GenesisDoc.Accounts.Permissions.Base]
        Perms = "send | call | name | proposal | input | hasRole"
        SetBit = "send | call | name | proposal | input | hasRole"

  [[GenesisDoc.Accounts]]
    Address = "C6065351DD4B18074D62AF10185C6F33A7EE929A"
    PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"B3A63AFC90B5A536E3E17F642BB4B55EC8CFF451968ABF4AE582E594C5B20BCA\"}"
    Amount = 9999999999
    Name = "Participant_5"
    [GenesisDoc.Accounts.Permissions]
      [GenesisDoc.Accounts.Permissions.Base]
        Perms = "send | call | name | proposal | input | hasRole"
        SetBit = "send | call | name | proposal | input | hasRole"

  [[GenesisDoc.Accounts]]
    Address = "D0F92797CBFBEB70E59BFC9B56A18A47750F3490"
    PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"9B9F7FAA139CABCAD4043CBD88B4708E8CCCB80481F1D24825676C2A3389A349\"}"
    Amount = 9999999999
    Name = "Participant_6"
    [GenesisDoc.Accounts.Permissions]
      [GenesisDoc.Accounts.Permissions.Base]
        Perms = "send | call | name | proposal | input | hasRole"
        SetBit = "send | call | name | proposal | input | hasRole"

  [[GenesisDoc.Accounts]]
    Address = "C2BCE742A7B3C90FE8346C220A017852A66DD7B5"
    PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"1ED293815854324EAE6061B935EE6557ABD38D783D45D5ED2C52AB0E470C7380\"}"
    Amount = 9999999999
    Name = "Participant_7"
    [GenesisDoc.Accounts.Permissions]
      [GenesisDoc.Accounts.Permissions.Base]
        Perms = "send | call | name | proposal | input | hasRole"
        SetBit = "send | call | name | proposal | input | hasRole"

  [[GenesisDoc.Accounts]]
    Address = "1BBC6FA2433E3A93B48F9D1AA6F704918B096C3E"
    PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"9641CC232563F0E694B76F21EF9624E274B739B11CA21439DDF7AA40C1F55AB5\"}"
    Amount = 9999999999
    Name = "Participant_8"
    [GenesisDoc.Accounts.Permissions]
      [GenesisDoc.Accounts.Permissions.Base]
        Perms = "send | call | name | proposal | input | hasRole"
        SetBit = "send | call | name | proposal | input | hasRole"

  [[GenesisDoc.Accounts]]
    Address = "F0E9B43EEC81E8E318B28ADC21617AD0C98EAE9E"
    PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"30369E16771FBC8346E72504EB4110EAF8103497823331154125945748F44962\"}"
    Amount = 9999999999
    Name = "Participant_9"
    [GenesisDoc.Accounts.Permissions]
      [GenesisDoc.Accounts.Permissions.Base]
        Perms = "send | call | name | proposal | input | hasRole"
        SetBit = "send | call | name | proposal | input | hasRole"

  [[GenesisDoc.Validators]]
    Address = "44E32AD7C983146F6D8B4DBF6D22959E89A92F67"
    PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"94E6D699FC57B3575E8E5A56CA18CF9632430A31D566705B4C3CAA06134F58B0\"}"
    Amount = 9999999999
    Name = "Full_0"

    [[GenesisDoc.Validators.UnbondTo]]
      Address = "44E32AD7C983146F6D8B4DBF6D22959E89A92F67"
      PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"94E6D699FC57B3575E8E5A56CA18CF9632430A31D566705B4C3CAA06134F58B0\"}"
      Amount = 9999999999

  [[GenesisDoc.Validators]]
    Address = "1A723EC91525B0677A86368A5F20F68B25D44C6E"
    PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"73757FAA063959ECDACAB1D845786F196A792811EA0D1E638AD0A1BD8B1DF03B\"}"
    Amount = 9999999999
    Name = "Full_1"

    [[GenesisDoc.Validators.UnbondTo]]
      Address = "1A723EC91525B0677A86368A5F20F68B25D44C6E"
      PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"73757FAA063959ECDACAB1D845786F196A792811EA0D1E638AD0A1BD8B1DF03B\"}"
      Amount = 9999999999

  [[GenesisDoc.Validators]]
    Address = "6E536049FB8134A3DD55AE26612E496FEBC856D5"
    PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"94D4F25C19FCEC53711FC77B839EBEF299E8467DCFB73A7AB504DE09912EBDFB\"}"
    Amount = 9999999999
    Name = "Full_2"

    [[GenesisDoc.Validators.UnbondTo]]
      Address = "6E536049FB8134A3DD55AE26612E496FEBC856D5"
      PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"94D4F25C19FCEC53711FC77B839EBEF299E8467DCFB73A7AB504DE09912EBDFB\"}"
      Amount = 9999999999

  [[GenesisDoc.Validators]]
    Address = "A72DF4F1AE055B11201123A9DDDCBC12E7E5DF2B"
    PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"A863FEAD151F388B781D62BEEA26712E59DD3AF0E2F478DA260F3C4AA5EE8904\"}"
    Amount = 9999999999
    Name = "Full_3"

    [[GenesisDoc.Validators.UnbondTo]]
      Address = "A72DF4F1AE055B11201123A9DDDCBC12E7E5DF2B"
      PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"A863FEAD151F388B781D62BEEA26712E59DD3AF0E2F478DA260F3C4AA5EE8904\"}"
      Amount = 9999999999

  [[GenesisDoc.Validators]]
    Address = "5603A906C480EB96803649C3D97F3075C849061C"
    PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"B0FD7AB0FAC3A68D864D273E8750E089E52000CC7561B9648BE049F549BA9A44\"}"
    Amount = 9999999999
    Name = "Full_4"

    [[GenesisDoc.Validators.UnbondTo]]
      Address = "5603A906C480EB96803649C3D97F3075C849061C"
      PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"B0FD7AB0FAC3A68D864D273E8750E089E52000CC7561B9648BE049F549BA9A44\"}"
      Amount = 9999999999

  [[GenesisDoc.Validators]]
    Address = "D584FFF08EB31E03AD83ACB35928B01C008AD778"
    PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"328120F35B78653B64A8EE6C187D958E1C043B1F798DC4E78CF55369C0492BA6\"}"
    Amount = 9999999999
    Name = "Full_5"

    [[GenesisDoc.Validators.UnbondTo]]
      Address = "D584FFF08EB31E03AD83ACB35928B01C008AD778"
      PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"328120F35B78653B64A8EE6C187D958E1C043B1F798DC4E78CF55369C0492BA6\"}"
      Amount = 9999999999

  [[GenesisDoc.Validators]]
    Address = "A297DBBD7FF192CF9F4B3986F6D1FC219DDBB2C1"
    PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"6436F6CEA37A32D7551A9E86310F20B8E18471486AACBD864E098CB9EA28B02B\"}"
    Amount = 9999999999
    Name = "Full_6"

    [[GenesisDoc.Validators.UnbondTo]]
      Address = "A297DBBD7FF192CF9F4B3986F6D1FC219DDBB2C1"
      PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"6436F6CEA37A32D7551A9E86310F20B8E18471486AACBD864E098CB9EA28B02B\"}"
      Amount = 9999999999

  [[GenesisDoc.Validators]]
    Address = "7EFB026E3469760C8F2364A1070767264475D319"
    PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"9387024AD4E5C0645FCA292669889AACEDAF4B06D14E63D6C5C40F4B2A291588\"}"
    Amount = 9999999999
    Name = "Full_7"

    [[GenesisDoc.Validators.UnbondTo]]
      Address = "7EFB026E3469760C8F2364A1070767264475D319"
      PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"9387024AD4E5C0645FCA292669889AACEDAF4B06D14E63D6C5C40F4B2A291588\"}"
      Amount = 9999999999

  [[GenesisDoc.Validators]]
    Address = "8FE8F26E0F50BE83AD42CF6BC490D267532F3509"
    PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"511B281CC4EEF65148D361BBDFD9D645D2B8C271BA42B6EA959694606114FCDE\"}"
    Amount = 9999999999
    Name = "Full_8"

    [[GenesisDoc.Validators.UnbondTo]]
      Address = "8FE8F26E0F50BE83AD42CF6BC490D267532F3509"
      PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"511B281CC4EEF65148D361BBDFD9D645D2B8C271BA42B6EA959694606114FCDE\"}"
      Amount = 9999999999

  [[GenesisDoc.Validators]]
    Address = "A6227532C81022F9E8E3C15D5F445CEB28E40B18"
    PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"505B20308B035C5DD3D616810695FD7FE8AA77E4636E852C42D5A17D3CA7CFB0\"}"
    Amount = 9999999999
    Name = "Full_9"

    [[GenesisDoc.Validators.UnbondTo]]
      Address = "A6227532C81022F9E8E3C15D5F445CEB28E40B18"
      PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"505B20308B035C5DD3D616810695FD7FE8AA77E4636E852C42D5A17D3CA7CFB0\"}"
      Amount = 9999999999

[Tendermint]
  Seeds = ""
  SeedMode = false
  PersistentPeers = ""
  ListenAddress = "tcp://0.0.0.0:26656"
  ExternalAddress = ""
  Moniker = ""
  TendermintRoot = ".burrow"
  AuthorizedPeers = ""
  CreateEmptyBlocks = true
  CreateEmptyBlocksInterval = 0

[Execution]
  CallStackMaxDepth = 0
  DataStackInitialCapacity = 1024
  DataStackMaxDepth = 0

[Keys]
  GRPCServiceEnabled = true
  AllowBadFilePermissions = false
  RemoteAddress = ""
  KeysDirectory = ".keys"

[RPC]
  [RPC.Info]
    Enabled = true
    ListenAddress = "tcp://127.0.0.1:26658"
  [RPC.Profiler]
    Enabled = false
    ListenAddress = "tcp://127.0.0.1:6060"
  [RPC.GRPC]
    Enabled = true
    ListenAddress = "127.0.0.1:10997"
  [RPC.Metrics]
    Enabled = false
    ListenAddress = "tcp://127.0.0.1:9102"
    MetricsPath = "/metrics"
    BlockSampleSize = 100

[Logging]
  ExcludeTrace = false
  NonBlocking = false
  [Logging.RootSink]
    [Logging.RootSink.Output]
      OutputType = "stderr"
      Format = "json"

